name: Build and Release

on:
  push:
    tags:
      - 'v*'      # build/release only on version tags, like v1.2.0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up AutoHotkey
        uses: auto-hotkey/setup-ahk@v1 # or set up PowerShell and ahk2exe as needed

      - name: Run Build Script
        run: pwsh ./_build/build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./_build/*.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./_build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
